# -*- coding: utf-8 -*-
"""notebook_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xSON1TYqsRpxke7D8AWSyY2ScSsfOy1r

# **NOTEBOOK 02: EDA**

---

MedMind Capstone — Exploratory Data Analysis
Loads the cleaned DABE dataset and produces all visualisations
needed for the Results chapter and Research Dashboard.

### **1. Setup and Load Data**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

plt.rcParams['figure.figsize'] = (12, 6)
plt.rcParams['figure.dpi'] = 150
plt.rcParams['font.size'] = 11
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 12
sns.set_style("whitegrid")
sns.set_palette("Set2")

CLEAN_PATH = "/content/dabe_clean_full.csv"
df = pd.read_csv(CLEAN_PATH)
print(f"Dataset loaded: {df.shape[0]} rows × {df.shape[1]} columns")
print(f"Universities: {df['University'].nunique()}")
print(f"\nColumns: {df.columns.tolist()}")
df.head()

"""### **2. Demographics summary**"""

df = pd.read_csv(CLEAN_PATH)
print(f"Dataset loaded: {df.shape[0]} rows × {df.shape[1]} columns")
print(f"Universities: {df['University'].nunique()}")
df.head()

"""**2.1 Gender**"""

print("\n--- Gender ---")
gender_counts = df["gender"].value_counts()
gender_pct = df["gender"].value_counts(normalize=True) * 100
for g in gender_counts.index:
    print(f"  {g}: {gender_counts[g]} ({gender_pct[g]:.1f}%)")

"""**2.2 Age**"""

print(f"\n--- Age ---")
print(f"  Mean: {df['Age'].mean():.1f}, Median: {df['Age'].median():.0f}, "
      f"SD: {df['Age'].std():.1f}, Range: {df['Age'].min():.0f}-{df['Age'].max():.0f}")

"""**2.3 Course Year**"""

print("\n--- Course Year ---")

year_counts = df["course_year"].value_counts().sort_index()
for y in year_counts.index:
    print(f"  Year {int(y)}: {year_counts[y]} ({year_counts[y]/len(df)*100:.1f}%)")

"""**2.4 Other demographics**"""

print("\n--- Sexual Orientation ---")
print(df["orientation"].value_counts().to_string())

print("\n--- Work Status ---")
print(df["works"].value_counts().to_string())

print(f"\n--- Fellowship ---")
print(f"  Yes: {df['has_fellowship'].sum()} ({df['has_fellowship'].mean()*100:.1f}%)")
print(f"  No:  {(df['has_fellowship']==0).sum()} ({(df['has_fellowship']==0).mean()*100:.1f}%)")

print(f"\n--- Attendance (1-6 scale) ---")
print(f"  Mean: {df['attendance'].mean():.1f}, Median: {df['attendance'].median():.0f}")

"""### **3. Demographic Plots**"""

print("\n" + "=" * 60)
print("PLOTTING DEMOGRAPHIC VARIABLES")
print("=" * 60)

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# Gender pie
gender_counts = df["gender"].value_counts()
colors_gender = {'Female': '#FF9999', 'Male': '#66B2FF', 'Other': '#99FF99'}
axes[0].pie(gender_counts, labels=gender_counts.index, autopct='%1.1f%%',
            colors=[colors_gender.get(g, '#ccc') for g in gender_counts.index],
            startangle=90)
axes[0].set_title('Gender Distribution')

# Age histogram
axes[1].hist(df['Age'], bins=30, color='#66B2FF', edgecolor='white', alpha=0.8)
axes[1].axvline(df['Age'].mean(), color='red', linestyle='--',
                label=f"Mean: {df['Age'].mean():.1f}")
axes[1].set_xlabel('Age')
axes[1].set_ylabel('Count')
axes[1].set_title('Age Distribution')
axes[1].legend()

# Course year bar
year_counts = df["course_year"].value_counts().sort_index()
axes[2].bar(year_counts.index.astype(int), year_counts.values, color='#66B2FF', edgecolor='white')
axes[2].set_xlabel('Course Year')
axes[2].set_ylabel('Count')
axes[2].set_title('Students per Course Year')
axes[2].set_xticks(range(1, 7))

plt.tight_layout()
plt.savefig("fig_01_demographics.png", bbox_inches='tight')
plt.show()

"""**3.1 Extended demographic plots**"""

print("\n" + "=" * 60)
print("EXTENDED DENOGRAPHICS PLOTS")
print("=" * 60)

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# Sexual orientation
orient_counts = df['orientation'].value_counts()
axes[0].barh(orient_counts.index, orient_counts.values, color='#9B59B6', edgecolor='white')
for i, (idx, val) in enumerate(orient_counts.items()):
    axes[0].text(val + 20, i, f'{val} ({val/len(df)*100:.1f}%)', va='center', fontsize=10)
axes[0].set_title('Sexual Orientation')
axes[0].spines['top'].set_visible(False)
axes[0].spines['right'].set_visible(False)

# Work status
work_counts = df['works'].value_counts()
axes[1].pie(work_counts, labels=work_counts.index, autopct='%1.1f%%',
            colors=['#2ECC71', '#E74C3C', '#F39C12'], startangle=90)
axes[1].set_title('Work Status')

# Fellowship
fell_counts = pd.Series({'Yes': df['has_fellowship'].sum(),
                          'No': (df['has_fellowship']==0).sum()})
axes[2].pie(fell_counts, labels=fell_counts.index, autopct='%1.1f%%',
            colors=['#3498DB', '#BDC3C7'], startangle=90)
axes[2].set_title('Has Fellowship/Scholarship')

plt.tight_layout()
plt.savefig("fig_02_demographics_extended.png", bbox_inches='tight')
plt.show()

"""### **4. Target Variable Prevalence**"""

print("\n" + "=" * 60)
print("TARGET VARIABLE PREVALENCE")
print("=" * 60)

targets = {
    'target_depression_clinical': 'Clinical Depression\n(BDI ≥ 20)',
    'target_burnout': 'Burnout\n(EX ≥ 2.8 & CY ≥ 2.25)',
    'target_anxiety_high': 'High Trait Anxiety\n(STAI-T ≥ 56)',
    'target_suicidal_ideation': 'Suicidal Ideation\n(B9 > 0)'
}

prevalences = {}
for col, label in targets.items():
    prev = df[col].mean() * 100
    n = df[col].sum()
    prevalences[label] = prev
    print(f"  {label.replace(chr(10), ' ')}: {n} ({prev:.1f}%)")

fig, ax = plt.subplots(figsize=(8, 3))
bars = ax.bar(prevalences.keys(), prevalences.values(),
              color=['#FF6B6B', '#FFA07A', '#FFD700', '#FF4444'],
              edgecolor='white', linewidth=1.5)

for bar, pct in zip(bars, prevalences.values()):
    ax.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 0.5,
            f'{pct:.1f}%', ha='center', va='bottom', fontweight='bold', fontsize=13)

ax.set_ylabel('Prevalence (%)')
ax.set_title('Mental Health Outcome Prevalence (n = 5,216)')
ax.set_ylim(0, max(prevalences.values()) + 5)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig("fig_03_prevalence.png", bbox_inches='tight')
plt.show()

"""### **5. Composite Score Distributions**"""

print("\n" + "=" * 60)
print("COMPOSITE SCORE DISTRIBUTIONS")
print("=" * 60)

composites = {
    'bdi_total': ('BDI-II Depression Total', 'Score (0-63)'),
    'mbi_exhaustion': ('MBI-SS Exhaustion', 'Mean Score (0-6)'),
    'mbi_cynicism': ('MBI-SS Cynicism', 'Mean Score (0-6)'),
    'mbi_efficacy': ('MBI-SS Academic Efficacy', 'Mean Score (0-6)'),
    'stai_state_total': ('STAI State Anxiety', 'Score (20-80)'),
    'stai_trait_total': ('STAI Trait Anxiety', 'Score (20-80)'),
    'empathy_total': ('Jefferson Empathy Scale', 'Score (20-140)')
}

fig, axes = plt.subplots(2, 4, figsize=(20, 10))
axes = axes.flatten()

for i, (col, (title, xlabel)) in enumerate(composites.items()):
    ax = axes[i]
    data = df[col].dropna()
    ax.hist(data, bins=40, color='#66B2FF', edgecolor='white', alpha=0.8, density=True)
    ax.axvline(data.mean(), color='red', linestyle='--', linewidth=1.5,
               label=f'Mean: {data.mean():.1f}')
    ax.axvline(data.median(), color='green', linestyle=':', linewidth=1.5,
               label=f'Median: {data.median():.1f}')
    ax.set_title(title)
    ax.set_xlabel(xlabel)
    ax.legend(fontsize=8)
    print(f"  {title}: mean={data.mean():.2f}, sd={data.std():.2f}, "
          f"median={data.median():.1f}, skew={data.skew():.2f}")

    axes[7].set_visible(False)
plt.suptitle('Distribution of Composite Psychological Scores', fontsize=16, y=1.02)
plt.tight_layout()
plt.savefig("fig_04_score_distributions.png", bbox_inches='tight')
plt.show()

"""### **6. BDI-II Depression Categories**"""

print("\n" + "=" * 60)
print("DEPRESSION SEVERITY BREAKDOWN")
print("=" * 60)

bdi_order = ['None/Minimal', 'Mild', 'Moderate', 'Severe']
bdi_colors = ['#2ECC71', '#F1C40F', '#E67E22', '#E74C3C']
bdi_counts = df['depression_category'].value_counts().reindex(bdi_order)

for cat in bdi_order:
    n = bdi_counts[cat]
    pct = n / len(df) * 100
    print(f"  {cat}: {n} ({pct:.1f}%)")

fig, axes = plt.subplots(1, 2, figsize=(10, 5))

axes[0].bar(bdi_order, bdi_counts.values, color=bdi_colors, edgecolor='white')
for i, (cat, n) in enumerate(zip(bdi_order, bdi_counts.values)):
    axes[0].text(i, n + 30, f'{n}\n({n/len(df)*100:.1f}%)', ha='center', fontsize=10)
axes[0].set_ylabel('Number of Students')
axes[0].set_title('BDI-II Depression Categories')
axes[0].spines['top'].set_visible(False)
axes[0].spines['right'].set_visible(False)

axes[1].pie(bdi_counts.values, labels=bdi_order, colors=bdi_colors,
            autopct='%1.1f%%', startangle=90)
axes[1].set_title('Depression Severity Distribution')

plt.tight_layout()
plt.savefig("fig_05_depression_categories.png", bbox_inches='tight')
plt.show()

"""### **7. STAI Trait Anxiety Categories**"""

print("\n" + "=" * 60)
print("STAI TRAIT ANXIETY CATEGORIES)")
print("=" * 60)

stai_order = ['Very Low', 'Low', 'Moderate', 'High', 'Very High']
stai_colors = ['#2ECC71', '#82E0AA', '#F1C40F', '#E67E22', '#E74C3C']
stai_counts = df['anxiety_trait_category'].value_counts().reindex(stai_order)

for cat in stai_order:
    n = stai_counts.get(cat, 0)
    pct = n / len(df) * 100
    print(f"  {cat}: {n} ({pct:.1f}%)")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

axes[0].bar(stai_order, stai_counts.values, color=stai_colors, edgecolor='white')
for i, (cat, n) in enumerate(zip(stai_order, stai_counts.values)):
    axes[0].text(i, n + 30, f'{n}\n({n/len(df)*100:.1f}%)', ha='center', fontsize=10)
axes[0].set_ylabel('Number of Students')
axes[0].set_title('STAI Trait Anxiety Categories')
axes[0].spines['top'].set_visible(False)
axes[0].spines['right'].set_visible(False)

axes[1].pie(stai_counts.values, labels=stai_order, colors=stai_colors,
            autopct='%1.1f%%', startangle=90)
axes[1].set_title('Trait Anxiety Severity Distribution')

plt.tight_layout()
plt.savefig("fig_06_anxiety_categories.png", bbox_inches='tight')
plt.show()

"""### **7. Year-by-Year Target Prevalence (RQ1)**"""

print("\n" + "=" * 60)
print("YEAR-BY-YEAR PROGRESSION (RQ1)")
print("=" * 60)

fig, axes = plt.subplots(2, 2, figsize=(12, 8))
axes = axes.flatten()

target_colors = ['#FF6B6B', '#FFA07A', '#FFD700', '#FF4444']

for i, (col, label) in enumerate(targets.items()):
    ax = axes[i]
    yearly = df.groupby('course_year')[col].mean() * 100
    clean_label = label.replace('\n', ' ')

    ax.plot(yearly.index, yearly.values, 'o-', color=target_colors[i],
            linewidth=2.5, markersize=8, markeredgecolor='white', markeredgewidth=2)

    for x, y in zip(yearly.index, yearly.values):
        ax.annotate(f'{y:.1f}%', (x, y), textcoords="offset points",
                    xytext=(0, 12), ha='center', fontsize=10, fontweight='bold')

    ax.set_xlabel('Course Year')
    ax.set_ylabel('Prevalence (%)')
    ax.set_title(clean_label)
    ax.set_xticks(range(1, 7))
    ax.set_xlim(0.5, 6.5)
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

    print(f"\n  {clean_label}:")
    for yr in range(1, 7):
        val = yearly.get(yr, 0)
        print(f"    Year {yr}: {val:.1f}%")

plt.suptitle('Mental Health Outcomes by Course Year', fontsize=16, y=1.02)
plt.tight_layout()
plt.savefig("fig_07_year_progression_targets.png", bbox_inches='tight')
plt.show()

"""### **8. Year-by-Year Composite Scores + Year 1 vs 6 Tests**"""

print("\n" + "=" * 60)
print("YEAR-BY-YEAR COMPOSITE SCORES")
print("=" * 60)

score_cols = ['bdi_total', 'mbi_exhaustion', 'mbi_cynicism',
              'mbi_efficacy', 'stai_trait_total', 'empathy_total']
score_labels = ['BDI-II Depression', 'MBI Exhaustion', 'MBI Cynicism',
                'MBI Efficacy', 'STAI Trait Anxiety', 'Jefferson Empathy']

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()

for i, (col, label) in enumerate(zip(score_cols, score_labels)):
    ax = axes[i]
    yearly_mean = df.groupby('course_year')[col].mean()
    yearly_se = df.groupby('course_year')[col].sem()

    ax.errorbar(yearly_mean.index, yearly_mean.values, yerr=yearly_se.values * 1.96,
                fmt='o-', color='#3498DB', linewidth=2, markersize=7,
                capsize=5, capthick=1.5, markeredgecolor='white')
    ax.set_xlabel('Course Year')
    ax.set_ylabel('Mean Score')
    ax.set_title(label)
    ax.set_xticks(range(1, 7))
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

plt.suptitle('Composite Scores by Course Year (Mean ± 95% CI)', fontsize=16, y=1.02)
plt.tight_layout()
plt.savefig("fig_08_year_progression_scores.png", bbox_inches='tight')
plt.show()

print("\n--- Year 1 vs Year 6 Comparison (Mann-Whitney U) ---")
for col, label in zip(score_cols, score_labels):
    y1 = df[df['course_year'] == 1][col].dropna()
    y6 = df[df['course_year'] == 6][col].dropna()
    stat, p = stats.mannwhitneyu(y1, y6, alternative='two-sided')
    effect_size = abs(y6.mean() - y1.mean()) / df[col].std()
    direction = "↑" if y6.mean() > y1.mean() else "↓"
    print(f"  {label}: Y1={y1.mean():.2f}, Y6={y6.mean():.2f} {direction}, "
          f"d={effect_size:.3f}, p={p:.4f} {'***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'}")

"""### **9. Gender**

**9.1 Target Prevalence + Chi-Square**
"""

print("\n" + "=" * 60)
print("GENDER ANALYSIS — TARGET PREVALENCE")
print("=" * 60)

df_gender = df[df['gender'].isin(['Male', 'Female'])].copy()

target_short = {
    'target_depression_clinical': 'Depression',
    'target_burnout': 'Burnout',
    'target_anxiety_high': 'Anxiety',
    'target_suicidal_ideation': 'Suicidal\nIdeation'
}

fig, ax = plt.subplots(figsize=(8, 4))

x = np.arange(len(target_short))
width = 0.35

male_prev = [df_gender[df_gender['gender'] == 'Male'][t].mean() * 100 for t in target_short.keys()]
female_prev = [df_gender[df_gender['gender'] == 'Female'][t].mean() * 100 for t in target_short.keys()]

bars_m = ax.bar(x - width/2, male_prev, width, label='Male', color='#66B2FF', edgecolor='white')
bars_f = ax.bar(x + width/2, female_prev, width, label='Female', color='#FF9999', edgecolor='white')

for bar, val in zip(bars_m, male_prev):
    ax.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 0.5,
            f'{val:.1f}%', ha='center', va='bottom', fontsize=10)
for bar, val in zip(bars_f, female_prev):
    ax.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 0.5,
            f'{val:.1f}%', ha='center', va='bottom', fontsize=10)

ax.set_ylabel('Prevalence (%)')
ax.set_title('Mental Health Outcomes by Gender')
ax.set_xticks(x)
ax.set_xticklabels(target_short.values())
ax.legend()
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig("fig_09_gender_targets.png", bbox_inches='tight')
plt.show()

print("\n--- Chi-Square Tests (Gender × Target) ---")
for col, label in target_short.items():
    ct = pd.crosstab(df_gender['gender'], df_gender[col])
    chi2, p, dof, expected = stats.chi2_contingency(ct)
    cramers_v = np.sqrt(chi2 / (len(df_gender) * (min(ct.shape) - 1)))
    print(f"  {label.replace(chr(10), ' ')}: χ²={chi2:.2f}, p={p:.4f}, Cramér's V={cramers_v:.3f} "
          f"{'***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'}")

"""**9.2 Composite Scores (Boxplots + Mann-Whitney)**"""

print("\n" + "=" * 60)
print("GENDER ANALYSIS — COMPOSITE SCORES")
print("=" * 60)

df_gender = df[df['gender'].isin(['Male', 'Female'])].copy()

fig, axes = plt.subplots(2, 3, figsize=(16, 10))
axes = axes.flatten()

for i, (col, label) in enumerate(zip(score_cols, score_labels)):
    ax = axes[i]
    sns.boxplot(data=df_gender, x='gender', y=col, ax=ax,
                palette={'Male': '#66B2FF', 'Female': '#FF9999'},
                flierprops=dict(marker='o', markersize=2, alpha=0.3))
    ax.set_title(label)
    ax.set_xlabel('')

    male_data = df_gender[df_gender['gender'] == 'Male'][col].dropna()
    female_data = df_gender[df_gender['gender'] == 'Female'][col].dropna()
    stat, p = stats.mannwhitneyu(male_data, female_data, alternative='two-sided')
    sig = '***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'
    ax.set_xlabel(f'p={p:.4f} {sig}')
    print(f"  {label}: Male={male_data.mean():.2f}, Female={female_data.mean():.2f}, p={p:.4f} {sig}")

plt.suptitle('Composite Scores by Gender', fontsize=16, y=1.02)
plt.tight_layout()
plt.savefig("fig_10_gender_scores.png", bbox_inches='tight')
plt.show()

"""**9.3 Year Interaction (all 4 targets)**"""

print("\n" + "=" * 60)
print("GENDER × YEAR INTERACTION — ALL TARGETS")
print("=" * 60)

df_gender = df[df['gender'].isin(['Male', 'Female'])].copy()

fig, axes = plt.subplots(2, 2, figsize=(10, 8))
axes = axes.flatten()

for i, (col, label) in enumerate(target_short.items()):
    ax = axes[i]
    clean_label = label.replace('\n', ' ')

    for g, color, marker in [('Female', '#FF9999', 'o'), ('Male', '#66B2FF', 's')]:
        subset = df_gender[df_gender['gender'] == g]
        yearly = subset.groupby('course_year')[col].mean() * 100
        ax.plot(yearly.index, yearly.values, f'{marker}-', color=color,
                linewidth=2.5, markersize=8, label=g, markeredgecolor='white')

    ax.set_xlabel('Course Year')
    ax.set_ylabel('Prevalence (%)')
    ax.set_title(f'{clean_label} by Gender and Year')
    ax.set_xticks(range(1, 7))
    ax.legend()
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

plt.suptitle('Gender × Course Year Interaction for All Targets', fontsize=16, y=1.02)
plt.tight_layout()
plt.savefig("fig_11_gender_year_all_targets.png", bbox_inches='tight')
plt.show()

"""### **10. Sexual Orientation × Targets**"""

print("\n" + "=" * 60)
print("SEXUAL ORIENTATION ANALYSIS")
print("=" * 60)

# Binary: heterosexual vs non-heterosexual
df['orient_group'] = np.where(df['orientation_non_hetero'] == 1,
                               'Non-heterosexual', 'Heterosexual')

fig, ax = plt.subplots(figsize=(8, 4))

x = np.arange(len(target_short))
width = 0.35

het_prev = [df[df['orient_group'] == 'Heterosexual'][t].mean() * 100 for t in target_short.keys()]
nonhet_prev = [df[df['orient_group'] == 'Non-heterosexual'][t].mean() * 100 for t in target_short.keys()]

bars_h = ax.bar(x - width/2, het_prev, width, label='Heterosexual', color='#3498DB', edgecolor='white')
bars_n = ax.bar(x + width/2, nonhet_prev, width, label='Non-heterosexual', color='#E74C3C', edgecolor='white')

for bar, val in zip(bars_h, het_prev):
    ax.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 0.5,
            f'{val:.1f}%', ha='center', va='bottom', fontsize=10)
for bar, val in zip(bars_n, nonhet_prev):
    ax.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 0.5,
            f'{val:.1f}%', ha='center', va='bottom', fontsize=10)

ax.set_ylabel('Prevalence (%)')
ax.set_title('Mental Health Outcomes by Sexual Orientation')
ax.set_xticks(x)
ax.set_xticklabels(target_short.values())
ax.legend()
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig("fig_12_orientation_targets.png", bbox_inches='tight')
plt.show()

print("\n--- Chi-Square Tests (Orientation × Target) ---")
for col, label in target_short.items():
    ct = pd.crosstab(df['orient_group'], df[col])
    chi2, p, dof, expected = stats.chi2_contingency(ct)
    cramers_v = np.sqrt(chi2 / (len(df) * (min(ct.shape) - 1)))
    print(f"  {label.replace(chr(10), ' ')}: χ²={chi2:.2f}, p={p:.4f}, V={cramers_v:.3f} "
          f"{'***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'}")

"""### **11. Correlation Matrix**"""

print("\n" + "=" * 60)
print("CORRELATION ANALYSIS")
print("=" * 60)

corr_cols = ['bdi_total', 'mbi_exhaustion', 'mbi_cynicism',
             'mbi_efficacy', 'stai_state_total', 'stai_trait_total',
             'empathy_total']
corr_labels = ['Depression\n(BDI)', 'Exhaustion', 'Cynicism', 'Efficacy',
               'State\nAnxiety', 'Trait\nAnxiety', 'Empathy']

corr_matrix = df[corr_cols].corr(method='spearman')

fig, ax = plt.subplots(figsize=(8, 6))
mask = np.triu(np.ones_like(corr_matrix, dtype=bool), k=1)
sns.heatmap(corr_matrix, mask=mask, annot=True, fmt='.2f', cmap='RdBu_r',
            center=0, vmin=-1, vmax=1, square=True,
            xticklabels=corr_labels, yticklabels=corr_labels,
            linewidths=0.5, ax=ax)
ax.set_title('Spearman Correlations Between Composite Scores')
plt.tight_layout()
plt.savefig("fig_13_correlation_matrix.png", bbox_inches='tight')
plt.show()

print("\nStrongest correlations (|r| > 0.3):")
for i in range(len(corr_cols)):
    for j in range(i+1, len(corr_cols)):
        r = corr_matrix.iloc[i, j]
        if abs(r) > 0.3:
            print(f"  {corr_cols[i]} × {corr_cols[j]}: r={r:.3f}")

"""### **12. Social Support Analysis**"""

print("\n" + "=" * 60)
print("SOCIAL SUPPORT ANALYSIS")
print("=" * 60)

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Panel 1: Number of close people
ax = axes[0, 0]
support_n_labels = {1: 'None', 2: '1-2', 3: '3-5', 4: '5+'}
support_n = df['social_support_n'].map(support_n_labels).value_counts().reindex(
    ['None', '1-2', '3-5', '5+'])
ax.bar(support_n.index, support_n.values, color='#3498DB', edgecolor='white')
for i, (idx, val) in enumerate(support_n.items()):
    ax.text(i, val + 20, f'{val}\n({val/len(df)*100:.1f}%)', ha='center', fontsize=10)
ax.set_ylabel('Count')
ax.set_title('Number of Close Support People')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Panel 2: Support quality scores (reversed, higher = better)
ax = axes[0, 1]
support_q_cols = ['social_support_q2', 'social_support_q3', 'social_support_q4']
support_q_labels = ['Emotional\nSupport', 'Practical\nHelp', 'Advice/\nGuidance']
support_means = [df[c].mean() for c in support_q_cols]
support_ses = [df[c].sem() * 1.96 for c in support_q_cols]
ax.bar(support_q_labels, support_means, yerr=support_ses, color='#2ECC71',
       edgecolor='white', capsize=8)
ax.set_ylabel('Mean Score (1=None, 5=A lot)')
ax.set_title('Quality of Social Support')
ax.set_ylim(0, 5.5)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

for i, (m, s) in enumerate(zip(support_means, support_ses)):
    print(f"  {support_q_labels[i].replace(chr(10), ' ')}: mean={m:.2f}")

# Panel 3: Support count vs depression
ax = axes[1, 0]
support_dep = df.groupby('social_support_n')['target_depression_clinical'].mean() * 100
ax.bar(support_dep.index.map(support_n_labels), support_dep.values,
       color='#E74C3C', edgecolor='white')
for i, (idx, val) in enumerate(support_dep.items()):
    ax.text(i, val + 0.5, f'{val:.1f}%', ha='center', fontsize=10, fontweight='bold')
ax.set_ylabel('Depression Prevalence (%)')
ax.set_title('Depression Rate by Social Support Level')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Panel 4: Support count vs suicidal ideation
ax = axes[1, 1]
support_si = df.groupby('social_support_n')['target_suicidal_ideation'].mean() * 100
ax.bar(support_si.index.map(support_n_labels), support_si.values,
       color='#FF4444', edgecolor='white')
for i, (idx, val) in enumerate(support_si.items()):
    ax.text(i, val + 0.3, f'{val:.1f}%', ha='center', fontsize=10, fontweight='bold')
ax.set_ylabel('Suicidal Ideation Prevalence (%)')
ax.set_title('Suicidal Ideation Rate by Social Support Level')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig("fig_14_social_support.png", bbox_inches='tight')
plt.show()

"""### **13. Academic Variables**"""

print("\n" + "=" * 60)
print("ACADEMIC VARIABLES ANALYSIS")
print("=" * 60)

fig, axes = plt.subplots(1, 3, figsize=(16, 5))

# Effort-grade match (1=Lower, 2=Concordant, 3=Higher)
ax = axes[0]
effort_labels = {1: 'Grades < Effort', 2: 'Concordant', 3: 'Grades > Effort'}
effort_counts = df['acad_effort_match'].map(effort_labels).value_counts().reindex(
    ['Grades < Effort', 'Concordant', 'Grades > Effort'])
ax.bar(effort_counts.index, effort_counts.values, color='#9B59B6', edgecolor='white')
for i, val in enumerate(effort_counts.values):
    ax.text(i, val + 20, f'{val}\n({val/len(df)*100:.1f}%)', ha='center', fontsize=9)
ax.set_title('Effort–Grade Match')
ax.set_ylabel('Count')
ax.tick_params(axis='x', rotation=15)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Satisfaction with studies (reversed, higher = better)
ax = axes[1]
sat_labels = {1: 'Not at all', 2: 'Somewhat', 3: 'Quite', 4: 'Very'}
sat_counts = df['acad_satisfaction_studies'].map(sat_labels).value_counts().reindex(
    ['Not at all', 'Somewhat', 'Quite', 'Very'])
ax.bar(sat_counts.index, sat_counts.values, color='#F39C12', edgecolor='white')
for i, val in enumerate(sat_counts.values):
    ax.text(i, val + 20, f'{val/len(df)*100:.1f}%', ha='center', fontsize=10)
ax.set_title('Satisfaction with Studies')
ax.set_ylabel('Count')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Effort-grade mismatch vs burnout
ax = axes[2]
effort_burnout = df.groupby('acad_effort_match')['target_burnout'].mean() * 100
ax.bar(effort_burnout.index.map(effort_labels), effort_burnout.values,
       color='#FFA07A', edgecolor='white')
for i, val in enumerate(effort_burnout.values):
    ax.text(i, val + 0.5, f'{val:.1f}%', ha='center', fontsize=10, fontweight='bold')
ax.set_ylabel('Burnout Prevalence (%)')
ax.set_title('Burnout Rate by Effort–Grade Match')
ax.tick_params(axis='x', rotation=15)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig("fig_15_academic_variables.png", bbox_inches='tight')
plt.show()

print(f"  Effort-grade match: {effort_counts.to_dict()}")
print(f"  Satisfaction studies: mean={df['acad_satisfaction_studies'].mean():.2f}")
print(f"  Satisfaction choice: mean={df['acad_satisfaction_choice'].mean():.2f}")

"""### **14. Perceived Problems**"""

print("\n" + "=" * 60)
print("PERCEIVED PROBLEMS ANALYSIS")
print("=" * 60)

prob_cols = [c for c in df.columns if c.startswith('prob_')]
prob_labels_clean = [c.replace('prob_', '').replace('_', ' ').title() for c in prob_cols]
prob_prevalence = df[prob_cols].mean() * 100

sort_idx = prob_prevalence.argsort()[::-1]
prob_sorted = prob_prevalence.iloc[sort_idx]
labels_sorted = [prob_labels_clean[i] for i in sort_idx]

fig, ax = plt.subplots(figsize=(8, 4))
bars = ax.barh(range(len(prob_sorted)), prob_sorted.values, color='#3498DB',
               edgecolor='white', alpha=0.85)
ax.set_yticks(range(len(labels_sorted)))
ax.set_yticklabels(labels_sorted)
ax.set_xlabel('Prevalence (%)')
ax.set_title('Perceived Problems Among Medical Students')
ax.invert_yaxis()

for bar, val in zip(bars, prob_sorted.values):
    ax.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height()/2.,
            f'{val:.1f}%', ha='left', va='center', fontsize=10)

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig("fig_16_perceived_problems.png", bbox_inches='tight')
plt.show()

for label, val in zip(labels_sorted, prob_sorted.values):
    print(f"  {label}: {val:.1f}%")

df['n_problems'] = sum(df[c] for c in prob_cols)
print(f"\n  Problems per student: mean={df['n_problems'].mean():.1f}, "
      f"median={df['n_problems'].median():.0f}, max={df['n_problems'].max()}")

"""### **15. Substance Use (all 4: tobacco, alcohol, cannabis, psychopharm)**"""

print("\n" + "=" * 60)
print("SUBSTANCE USE ANALYSIS")
print("=" * 60)

fig, axes = plt.subplots(2, 2, figsize=(14, 10))

# Panel 1: Tobacco (recoded 0=No, 1=Occasional, 2=Regular)
ax = axes[0, 0]
tobacco_labels = {0: 'No', 1: 'Occasional', 2: 'Regular'}
tobacco_counts = df['tobacco'].map(tobacco_labels).value_counts().reindex(['No', 'Occasional', 'Regular'])
ax.bar(tobacco_counts.index, tobacco_counts.values, color='#95A5A6', edgecolor='white')
for i, val in enumerate(tobacco_counts.values):
    ax.text(i, val + 20, f'{val/len(df)*100:.1f}%', ha='center', fontsize=10)
ax.set_ylabel('Count')
ax.set_title('Tobacco Use')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Panel 2: Alcohol (recoded 0-4)
ax = axes[0, 1]
alcohol_labels_map = {0: 'Never', 1: 'Occasional', 2: '1-2x/wk', 3: '2-3x/wk', 4: '3+/wk'}
alcohol_counts = df['alcohol'].map(alcohol_labels_map).value_counts().reindex(
    ['Never', 'Occasional', '1-2x/wk', '2-3x/wk', '3+/wk'])
ax.bar(alcohol_counts.index, alcohol_counts.values, color='#F39C12', edgecolor='white')
for i, val in enumerate(alcohol_counts.values):
    ax.text(i, val + 20, f'{val/len(df)*100:.1f}%', ha='center', fontsize=10)
ax.set_ylabel('Count')
ax.set_title('Alcohol Consumption')
ax.tick_params(axis='x', rotation=20)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Panel 3: Cannabis (recoded 0-3)
ax = axes[1, 0]
cannabis_labels_map = {0: 'Never', 1: 'Tried once', 2: 'Occasional', 3: 'Regular'}
cannabis_counts = df['cannabis'].map(cannabis_labels_map).value_counts().reindex(
    ['Never', 'Tried once', 'Occasional', 'Regular'])
ax.bar(cannabis_counts.index, cannabis_counts.values, color='#27AE60', edgecolor='white')
for i, val in enumerate(cannabis_counts.values):
    ax.text(i, val + 20, f'{val/len(df)*100:.1f}%', ha='center', fontsize=10)
ax.set_ylabel('Count')
ax.set_title('Cannabis Use')
ax.tick_params(axis='x', rotation=15)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Panel 4: Psychopharmaceuticals + breakdown by type
ax = axes[1, 1]
pharma_cols = ['pharma_anxiolytics', 'pharma_mood_stabilizers', 'pharma_antidepressants',
               'pharma_antipsychotics', 'pharma_other']
pharma_labels = ['Anxiolytics', 'Mood\nStabilizers', 'Anti-\ndepressants',
                 'Anti-\npsychotics', 'Other']
pharma_counts = [df[c].sum() for c in pharma_cols]
ax.bar(pharma_labels, pharma_counts, color='#E74C3C', edgecolor='white')
for i, val in enumerate(pharma_counts):
    ax.text(i, val + 3, f'{val}', ha='center', fontsize=10)
ax.set_ylabel('Count (among all students)')
ax.set_title(f'Psychopharmaceutical Types (n={df["takes_psychopharm"].sum()} users)')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.suptitle('Substance Use Patterns', fontsize=16, y=1.02)
plt.tight_layout()
plt.savefig("fig_17_substance_use.png", bbox_inches='tight')
plt.show()

print(f"  Psychopharmaceutical users: {df['takes_psychopharm'].sum()} ({df['takes_psychopharm'].mean()*100:.1f}%)")
for c, l in zip(pharma_cols, pharma_labels):
    print(f"    {l.replace(chr(10), '')}: {df[c].sum()}")

"""### **16. Life Events**"""

print("\n" + "=" * 60)
print("LIFE EVENTS ANALYSIS")
print("=" * 60)

eve_cols = ['eve_1', 'eve_2', 'eve_3', 'eve_4', 'eve_5']
eve_labels = {
    'eve_1': 'Serious illness/\naccident',
    'eve_2': 'Family member\nserious illness',
    'eve_3': 'Serious financial\nproblems',
    'eve_4': 'Relationship\nbreakup',
    'eve_5': 'Death of\nclose person'
}

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Panel 1: Life events prevalence
eve_prev = df[eve_cols].mean() * 100
ax = axes[0]
bars = ax.bar([eve_labels.get(c, c) for c in eve_cols], eve_prev.values,
              color='#E74C3C', edgecolor='white', alpha=0.8)
for bar, val in zip(bars, eve_prev.values):
    ax.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 0.5,
            f'{val:.1f}%', ha='center', fontsize=10)
ax.set_ylabel('Prevalence (%)')
ax.set_title('Stressful Life Events')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

for c in eve_cols:
    print(f"  {eve_labels.get(c, c).replace(chr(10), ' ')}: {df[c].mean()*100:.1f}%")

# Panel 2: Number of life events distribution
ax = axes[1]
df['n_life_events'] = df[eve_cols].sum(axis=1)
eve_dist = df['n_life_events'].value_counts().sort_index()
ax.bar(eve_dist.index, eve_dist.values, color='#9B59B6', edgecolor='white')
for x, y in zip(eve_dist.index, eve_dist.values):
    ax.text(x, y + 20, f'{y/len(df)*100:.1f}%', ha='center', fontsize=10)
ax.set_xlabel('Number of Life Events')
ax.set_ylabel('Count')
ax.set_title('Life Events per Student')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig("fig_18_life_events.png", bbox_inches='tight')
plt.show()

# %% CELL 21 — Life Events Dose-Response (ALL 4 targets)
print("LIFE EVENTS DOSE-RESPONSE — ALL TARGETS")
print("=" * 60)

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

target_colors_list = ['#FF6B6B', '#FFA07A', '#FFD700', '#FF4444']
target_labels_short = ['Depression', 'Burnout', 'Anxiety', 'Suicidal Ideation']

for i, (col, label) in enumerate(zip(targets.keys(), target_labels_short)):
    ax = axes[i]
    dose_resp = df.groupby('n_life_events')[col].mean() * 100
    ax.bar(dose_resp.index, dose_resp.values, color=target_colors_list[i], edgecolor='white')
    for x, y in zip(dose_resp.index, dose_resp.values):
        ax.text(x, y + 0.5, f'{y:.0f}%', ha='center', fontsize=10, fontweight='bold')
    ax.set_xlabel('Number of Life Events')
    ax.set_ylabel('Prevalence (%)')
    ax.set_title(f'{label} Rate by Life Events')
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

plt.suptitle('Dose-Response: Life Events and Mental Health Outcomes', fontsize=16, y=1.02)
plt.tight_layout()
plt.savefig("fig_19_life_events_dose_response.png", bbox_inches='tight')
plt.show()

"""### **17. Risk Factor Profiling: ALL 4 Targets**"""

print("\n" + "=" * 60)
print("RISK FACTOR PROFILING — ALL 4 TARGETS")
print("=" * 60)

compare_cols_list = ['mbi_exhaustion', 'mbi_cynicism', 'stai_trait_total',
                     'empathy_total', 'n_problems', 'n_life_events']
compare_labels = ['Exhaustion', 'Cynicism', 'Trait Anxiety',
                  'Empathy', 'N Problems', 'N Life Events']

for target_col, target_label in zip(targets.keys(), target_labels_short):
    print(f"\n--- {target_label}: Positive vs Negative (Mann-Whitney U) ---")
    pos = df[df[target_col] == 1]
    neg = df[df[target_col] == 0]

    for col, label in zip(compare_cols_list, compare_labels):
        stat, p = stats.mannwhitneyu(pos[col].dropna(), neg[col].dropna())
        d = abs(pos[col].mean() - neg[col].mean()) / df[col].std()
        sig = '***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'
        print(f"  {label}: Pos={pos[col].mean():.2f}, Neg={neg[col].mean():.2f}, "
              f"d={d:.2f} {sig}")

# Visualise for the two most clinically important targets
fig, axes = plt.subplots(2, 6, figsize=(24, 10))

for row, (target_col, target_label) in enumerate([
    ('target_depression_clinical', 'Depressed vs Not'),
    ('target_suicidal_ideation', 'Suicidal Ideation vs Not')
]):
    pos = df[df[target_col] == 1]
    neg = df[df[target_col] == 0]

    for j, (col, label) in enumerate(zip(compare_cols_list, compare_labels)):
        ax = axes[row, j]
        data_plot = pd.DataFrame({
            'Score': pd.concat([pos[col], neg[col]]),
            'Group': ['Positive'] * len(pos) + ['Negative'] * len(neg)
        })
        sns.violinplot(data=data_plot, x='Group', y='Score', ax=ax,
                       palette={'Positive': '#FF6B6B', 'Negative': '#2ECC71'},
                       inner='box', cut=0)
        ax.set_title(label, fontsize=11)
        ax.set_xlabel('')
        if j == 0:
            ax.set_ylabel(target_label)
        else:
            ax.set_ylabel('')

plt.suptitle('Risk Factor Profiles: Depression & Suicidal Ideation', fontsize=16, y=1.02)
plt.tight_layout()
plt.savefig("fig_20_risk_profiles.png", bbox_inches='tight')
plt.show()

"""### **18. Comorbidity Analysis**"""

print("\n" + "=" * 60)
print("COMORBIDITY ANALYSIS")
print("=" * 60)

target_list = list(targets.keys())
target_names = ['Depression', 'Burnout', 'Anxiety', 'Suicidal\nIdeation']

df['n_conditions'] = df[target_list].sum(axis=1)

print("Number of conditions per student:")
for n in range(5):
    count = (df['n_conditions'] == n).sum()
    pct = count / len(df) * 100
    print(f"  {n} conditions: {count} ({pct:.1f}%)")

fig, axes = plt.subplots(1, 2, figsize=(14, 6))

# Panel 1: Comorbidity count
ax = axes[0]
cond_counts = df['n_conditions'].value_counts().sort_index()
ax.bar(cond_counts.index, cond_counts.values, color='#8E44AD', edgecolor='white')
for x, y in zip(cond_counts.index, cond_counts.values):
    ax.text(x, y + 30, f'{y}\n({y/len(df)*100:.1f}%)', ha='center', fontsize=10)
ax.set_xlabel('Number of Conditions')
ax.set_ylabel('Number of Students')
ax.set_title('Mental Health Comorbidity')
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

# Panel 2: Co-occurrence heatmap
ax = axes[1]
target_df = df[target_list].copy()
target_df.columns = target_names
co_matrix = target_df.corr(method='spearman')
sns.heatmap(co_matrix, annot=True, fmt='.2f', cmap='YlOrRd',
            square=True, linewidths=0.5, ax=ax, vmin=0, vmax=1)
ax.set_title('Target Variable Co-occurrence')

plt.tight_layout()
plt.savefig("fig_21_comorbidity.png", bbox_inches='tight')
plt.show()

# Conditional probabilities
print("\n--- Conditional Probabilities ---")
for i, t1 in enumerate(target_list):
    for j, t2 in enumerate(target_list):
        if i >= j:
            continue
        n1 = target_labels_short[i]
        n2 = target_labels_short[j]
        both = ((df[t1] == 1) & (df[t2] == 1)).sum()
        p_2_given_1 = both / df[t1].sum() * 100
        p_1_given_2 = both / df[t2].sum() * 100
        print(f"  P({n2}|{n1}) = {p_2_given_1:.1f}%,  P({n1}|{n2}) = {p_1_given_2:.1f}%")

"""### **19. Preclinical vs Clinical**"""

print("\n" + "=" * 60)
print("PRECLINICAL (Years 1-3) vs CLINICAL (Years 4-6)")
print("=" * 60)

df['training_phase'] = np.where(df['course_year'] <= 3, 'Preclinical (1-3)', 'Clinical (4-6)')

preclin = df[df['training_phase'] == 'Preclinical (1-3)']
clin = df[df['training_phase'] == 'Clinical (4-6)']

fig, ax = plt.subplots(figsize=(10, 5))

x = np.arange(len(targets))
width = 0.35

preclin_prev = [preclin[t].mean() * 100 for t in targets.keys()]
clin_prev = [clin[t].mean() * 100 for t in targets.keys()]

bars_p = ax.bar(x - width/2, preclin_prev, width, label='Preclinical (1-3)',
                color='#3498DB', edgecolor='white')
bars_c = ax.bar(x + width/2, clin_prev, width, label='Clinical (4-6)',
                color='#E74C3C', edgecolor='white')

for bar, val in zip(bars_p, preclin_prev):
    ax.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 0.3,
            f'{val:.1f}%', ha='center', fontsize=10)
for bar, val in zip(bars_c, clin_prev):
    ax.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 0.3,
            f'{val:.1f}%', ha='center', fontsize=10)

ax.set_ylabel('Prevalence (%)')
ax.set_title('Preclinical vs Clinical Training Phase')
ax.set_xticks(x)
ax.set_xticklabels(['Depression', 'Burnout', 'Anxiety', 'Suicidal\nIdeation'])
ax.legend()
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.savefig("fig_22_preclinical_vs_clinical.png", bbox_inches='tight')
plt.show()

print("\n--- Chi-Square: Preclinical vs Clinical ---")
for col, label in zip(targets.keys(), target_labels_short):
    ct = pd.crosstab(df['training_phase'], df[col])
    chi2, p, dof, expected = stats.chi2_contingency(ct)
    print(f"  {label}: Preclin={preclin[col].mean()*100:.1f}%, Clin={clin[col].mean()*100:.1f}%, "
          f"χ²={chi2:.2f}, p={p:.4f} {'***' if p < 0.001 else '**' if p < 0.01 else '*' if p < 0.05 else 'ns'}")

"""### **20. Work Status × Targets**"""

print("\n" + "=" * 60)print("WORK STATUS × MENTAL HEALTH")
print("=" * 60)

fig, ax = plt.subplots(figsize=(12, 6))

work_groups = ['No', 'Part-time', 'Full-time']
x = np.arange(len(target_short))
width = 0.25

for i, work in enumerate(work_groups):
    prev = [df[df['works'] == work][t].mean() * 100 for t in target_short.keys()]
    bars = ax.bar(x + (i - 1) * width, prev, width, label=work, edgecolor='white')
    for bar, val in zip(bars, prev):
        ax.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 0.3,
                f'{val:.0f}%', ha='center', fontsize=8)

ax.set_ylabel('Prevalence (%)')
ax.set_title('Mental Health Outcomes by Work Status')
ax.set_xticks(x)
ax.set_xticklabels(target_short.values())
ax.legend()
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
plt.tight_layout()
plt.savefig("fig_23_work_status_targets.png", bbox_inches='tight')
plt.show()

for work in work_groups:
    subset = df[df['works'] == work]
    print(f"\n  {work} (n={len(subset)}):")
    for col, label in target_short.items():
        print(f"    {label.replace(chr(10), ' ')}: {subset[col].mean()*100:.1f}%")

# %% CELL 26 — Summary Table
print("\n" + "=" * 60)
print("SUMMARY TABLE")
print("=" * 60)

summary_data = {
    'Metric': [
        'Sample size', 'Universities', 'Female (%)', 'Mean age (SD)',
        '---',
        'Depression BDI ≥ 14 (%)', 'Depression BDI ≥ 20 (%)',
        'Burnout (%)', 'High Trait Anxiety (%)', 'Suicidal Ideation (%)',
        '---',
        'BDI-II Total', 'MBI Exhaustion', 'MBI Cynicism', 'MBI Efficacy',
        'STAI State', 'STAI Trait', 'Jefferson Empathy'
    ],
    'Value': [
        f"{len(df)}",
        f"{df['University'].nunique()}",
        f"{(df['gender']=='Female').sum()} ({(df['gender']=='Female').mean()*100:.1f}%)",
        f"{df['Age'].mean():.1f} ({df['Age'].std():.1f})",
        '---',
        f"{(df['bdi_total']>=14).sum()} ({(df['bdi_total']>=14).mean()*100:.1f}%)",
        f"{df['target_depression_clinical'].sum()} ({df['target_depression_clinical'].mean()*100:.1f}%)",
        f"{df['target_burnout'].sum()} ({df['target_burnout'].mean()*100:.1f}%)",
        f"{df['target_anxiety_high'].sum()} ({df['target_anxiety_high'].mean()*100:.1f}%)",
        f"{df['target_suicidal_ideation'].sum()} ({df['target_suicidal_ideation'].mean()*100:.1f}%)",
        '---',
        f"mean={df['bdi_total'].mean():.1f}, SD={df['bdi_total'].std():.1f}",
        f"mean={df['mbi_exhaustion'].mean():.2f}, SD={df['mbi_exhaustion'].std():.2f}",
        f"mean={df['mbi_cynicism'].mean():.2f}, SD={df['mbi_cynicism'].std():.2f}",
        f"mean={df['mbi_efficacy'].mean():.2f}, SD={df['mbi_efficacy'].std():.2f}",
        f"mean={df['stai_state_total'].mean():.1f}, SD={df['stai_state_total'].std():.1f}",
        f"mean={df['stai_trait_total'].mean():.1f}, SD={df['stai_trait_total'].std():.1f}",
        f"mean={df['empathy_total'].mean():.1f}, SD={df['empathy_total'].std():.1f}",
    ]
}

summary_df = pd.DataFrame(summary_data)
print(summary_df.to_string(index=False))

print(f"\n\n✅ EDA COMPLETE — 23 figures saved to working directory")
print("Figures: fig_01 through fig_23")